const random_words_list = [
    { word: "apple", hint: "A common fruit that keeps the doctor away" },
    { word: "guitar", hint: "A musical instrument with strings" },
    { word: "elephant", hint: "The largest land animal" },
    { word: "ocean", hint: "A vast body of salt water covering most of Earth" },
    { word: "javascript", hint: "A popular programming language for web development" },
    { word: "mountain", hint: "A large natural elevation of Earth's surface" },
    { word: "astronaut", hint: "A person trained for space travel" },
    { word: "butterfly", hint: "An insect with colorful wings" },
    { word: "telescope", hint: "An optical instrument for viewing distant objects" },
    { word: "computer", hint: "An electronic device for processing data" },
    { word: "penguin", hint: "A flightless bird found in Antarctica" },
    { word: "rainbow", hint: "A spectrum of colors in the sky after rain" },
    { word: "volcano", hint: "A mountain that erupts lava" },
    { word: "chocolate", hint: "A sweet treat made from cocoa" },
    { word: "bicycle", hint: "A two-wheeled vehicle powered by pedaling" },
    { word: "piano", hint: "A musical instrument with keys" },
    { word: "mirror", hint: "A reflective surface used for seeing oneself" },
    { word: "library", hint: "A place filled with books" },
    { word: "calendar", hint: "A system for organizing days and months" },
    { word: "umbrella", hint: "A tool used to protect against rain" },
    { word: "candle", hint: "A wax stick that burns to provide light" },
    { word: "tornado", hint: "A violent rotating column of air" },
    { word: "kangaroo", hint: "A marsupial from Australia" },
    { word: "diamond", hint: "A precious stone used in jewelry" },
    { word: "backpack", hint: "A bag carried on the back" },
    { word: "notebook", hint: "A book for writing notes" },
    { word: "sunflower", hint: "A yellow flower that follows the sun" },
    { word: "football", hint: "A popular sport played with a ball" },
    { word: "moonlight", hint: "The light that comes from the moon" },
    { word: "skeleton", hint: "The framework of bones in a body" },
    { word: "whisper", hint: "To speak in a soft, hushed voice" },
    { word: "giraffe", hint: "The tallest animal on land" },
    { word: "waterfall", hint: "A flow of water over a steep drop" },
    { word: "fireworks", hint: "Explosive lights seen during celebrations" },
    { word: "sandcastle", hint: "A structure made of sand at the beach" },
    { word: "carousel", hint: "A rotating amusement park ride" },
    { word: "airplane", hint: "A vehicle that flies in the sky" },
    { word: "binoculars", hint: "A tool for seeing distant objects clearly" },
    { word: "popcorn", hint: "A snack made from heated corn kernels" },
    { word: "snowflake", hint: "A unique ice crystal falling from the sky" },
    { word: "lighthouse", hint: "A tower with a bright light to guide ships" },
    { word: "tiger", hint: "A large striped feline" },
    { word: "clock", hint: "A device that tells time" },
    { word: "caterpillar", hint: "A larval stage of a butterfly" },
    { word: "glacier", hint: "A large mass of moving ice" },
    { word: "robot", hint: "A machine designed to perform tasks" },
    { word: "volleyball", hint: "A sport played with a net and ball" },
    { word: "jigsaw", hint: "A type of puzzle with many pieces" },
    { word: "watermelon", hint: "A large juicy fruit with a green rind" },
    { word: "parachute", hint: "A device used to slow a fall from high places" },
    { word: "sunglasses", hint: "Eyewear that protects from the sun" },
    { word: "paintbrush", hint: "A tool used for applying paint" },
    { word: "flashlight", hint: "A handheld light source" },
    { word: "avalanche", hint: "A rapid flow of snow down a mountain" },
    { word: "crocodile", hint: "A large reptile found in rivers" },
    { word: "chimney", hint: "A structure that lets smoke escape from a fireplace" },
    { word: "skateboard", hint: "A board with wheels used for skating" },
    { word: "compass", hint: "A tool that shows direction" },
    { word: "hurricane", hint: "A powerful storm with strong winds" },
    { word: "cheetah", hint: "The fastest land animal" },
    { word: "ladder", hint: "A tool used for climbing up or down" },
    { word: "telescope", hint: "A device for seeing distant stars" },
    { word: "dictionary", hint: "A book that defines words" },
    { word: "iceberg", hint: "A large floating mass of ice" },
    { word: "microscope", hint: "An instrument used to see tiny objects" },
    { word: "parrot", hint: "A colorful bird that can mimic speech" },
    { word: "fountain", hint: "A structure that sprays water" },
    { word: "sailboat", hint: "A boat powered by wind" },
    { word: "strawberry", hint: "A small red fruit with seeds on the outside" },
    { word: "trampoline", hint: "A jumping platform with springs" },
    { word: "zebra", hint: "An animal with black and white stripes" },
    { word: "firetruck", hint: "A vehicle used to put out fires" },
    { word: "ballerina", hint: "A female ballet dancer" },
    { word: "detective", hint: "A person who investigates mysteries" },
    { word: "rhinoceros", hint: "A large animal with a horn on its nose" },
    { word: "carousel", hint: "An amusement park ride that spins" },
    { word: "beehive", hint: "A home for bees" },
    { word: "bamboo", hint: "A plant that pandas love to eat" },
    { word: "mushroom", hint: "A fungi often used in cooking" },
    { word: "skyscraper", hint: "A very tall building" },
    { word: "peacock", hint: "A bird with colorful tail feathers" },
    { word: "boomerang", hint: "A curved object that returns when thrown" },
    { word: "honeycomb", hint: "A structure made by bees" },
    { word: "accordion", hint: "A musical instrument with a bellows" },
    { word: "submarine", hint: "A watercraft that travels underwater" },
    { word: "universe", hint: "All of space and everything in it" },
    { word: "rainforest", hint: "A dense forest with high rainfall" },
    { word: "scarecrow", hint: "A figure used to scare birds away from crops" }
];